name: 'Compile UEFI game'
on: 
    push:
        branches:
            - '*'
jobs:
    compile-deez:
        runs-on: ubuntu-latest
        steps:
            - name: Setup build environment
              run: |
               sudo apt update -y
               sudo apt install -y build-essential uuid-dev iasl git nasm python-is-python3
            
            - name: Create bootable ISO
              run: |
                dd if=/dev/zero of=disk.iso bs=1M count=4
                parted --script disk.iso \
                  mklabel gpt \
                  mkpart primary fat32 0% 100% \
                  set 1 esp on \
                  print
                sudo losetup --partscan /dev/loop23 disk.iso
                sudo mkfs.fat -F16 /dev/loop23p1
                sudo mkdir /mnt/game
                sudo mount /dev/loop23p1 /mnt/game
                sudo mkdir -p /mnt/game/efi/boot

            - uses: actions/checkout@v4
              name: Checkout repoistory
              with:
                submodules: recursive

            - name: Compile build tools
              run: | 
                make -C BaseTools
                . edksetup.sh
            
            - name: Compile base tools
              run: |
               make -C BaseTools

            - name: Setup build environment, and build
              run: | 
               export EDK_TOOLS_PATH=${{ github.workspace }}/BaseTools
               . edksetup.sh BaseTools
               build
               sudo cp Build/HackingGame/DEBUG_GCC5/X64/HackingGame/HackingGame/HackingGame/OUTPUT/HackingGame.efi /mnt/game/efi/boot/BOOTX64.efi
            
            - name: Unmount disk
              run: |
                sudo umount /mnt/game
                sudo losetup --detach /dev/loop23

            - name: Save build output
              uses: actions/upload-artifact@v3
              with:
                name: HackingGame EFI
                path: Build/HackingGame/DEBUG_GCC5/**/HackingGame/HackingGame/HackingGame

            - name: Save build output
              uses: actions/upload-artifact@v3
              with:
                name: HackingGame ISO
                path: disk-amd64.iso
